Enable async/await for Command.run
vapor/console-kit pull request #164
Opened 2021-12-19 23:01 UTC by twof

Allow's async function calls in Command.run

2021-12-19 23:02 UTC, twof commented on Package.swift
> +          ]
Necessary to fix a bug with `@main` on Big Sur

2021-12-19 23:04 UTC, twof commented on Tests/ConsoleKitTests/CommandErrorTests.swift
> -        XCTAssertThrowsError(try console.run(group, input: input), "Missing command is supposed to throw") { error in
A lot of these test updates are because `XCTAssertThrowsError` doesn't support async/await as far as I can tell, so we're manually try/catching.

2021-12-20 13:32 UTC, 0xTim commented
@twof this is a major break which we can't take in Vapor 4 obviously. You should be able to do it by adding `AnyAsyncCommand` and `AsyncCommand` types and using availability checks like we do for say Middleware. Definitely want to see this gain this capability however. 

Related to #161

2022-01-18 12:16 UTC, 0xTim requested changes
Lots of doc fixes but the main issue is that the new async stuff needs to be wrapped in compiler directives so it still compiles on earlier versions.

There's a discussion to be had about making `AnyAsyncCommand` conform to `AsyncCommand` to make it work a bit easier but for this use case I'm inclined to leave it. Thoughts @gwynne ?

2022-01-18 12:16 UTC, 0xTim commented on Sources/ConsoleKit/Command/Async/AsyncCommands.swift
> +    /// Adds a `Command` instance to the config.
```suggestion
    /// Adds an `AsyncCommand` instance to the config.
```

2022-01-18 12:16 UTC, 0xTim commented on Sources/ConsoleKit/Command/Async/AsyncCommands.swift
> +    ///     - command: Some `AnyCommand`. This type will be requested from the service container later.
```suggestion
    ///     - command: Some `AnyAsyncCommand`. This type will be requested from the service container later.
```

2022-01-18 12:16 UTC, 0xTim commented on Sources/ConsoleKit/Command/Async/AsyncCommands.swift
> +    /// Creates a `CommandGroup` for this `Commands`.
```suggestion
    /// Creates an `AsyncCommandGroup` for this `AsyncCommands`.
```

2022-01-18 12:16 UTC, 0xTim commented on Sources/ConsoleKit/Command/Async/AsyncCommands.swift
> +    ///     var config = Commands()
```suggestion
    ///     var config = AsyncCommands()
```

2022-01-18 12:16 UTC, 0xTim commented on Sources/ConsoleKit/Command/Async/AsyncCommands.swift
> +    /// - returns: A `CommandGroup` with commands and defaultCommand configured.
```suggestion
    /// - returns: An `AsyncCommandGroup` with commands and defaultCommand configured.
```

2022-01-18 12:16 UTC, 0xTim commented on Sources/ConsoleKit/Command/Async/AsyncCommands.swift
> +    /// Creates a new `ConfiguredCommands` struct. This is usually done by calling `resolve(for:)` on `Commands`.
```suggestion
    /// Creates a new `ConfiguredCommands` struct. This is usually done by calling `resolve(for:)` on `AsyncCommands`.
```

2022-01-18 12:16 UTC, 0xTim commented on Sources/ConsoleKit/Command/Async/AsyncCommandGroup.swift
> +///     var config = Commands()
```suggestion
///     var config = AsyncCommands()
```

2022-01-18 12:16 UTC, 0xTim commented on Sources/ConsoleKit/Command/Async/AsyncCommandGroup.swift
> +/// Usually you will use `Commands` to register commands and create a group.
```suggestion
/// Usually you will use `AsyncCommands` to register commands and create a group.
```

2022-01-18 12:16 UTC, 0xTim commented on Sources/ConsoleKit/Command/Async/AsyncCommands.swift
> +    ///     var config = Commands()
```suggestion
    ///     var config = AsyncCommands()
```

2022-01-18 12:16 UTC, 0xTim commented on Sources/ConsoleKit/Command/CommandGroup.swift
> +          return try `default`.run(using: &context)
The repo is 4 spaces
```suggestion
            return try `default`.run(using: &context)
```

2022-01-18 12:16 UTC, 0xTim commented on Sources/ConsoleKit/Command/CommandGroup.swift
> +          try command.run(using: &context)
```suggestion
            try command.run(using: &context)
```

2022-01-18 12:16 UTC, 0xTim commented on Sources/ConsoleKit/Command/Completion.swift
> +    // See `AnyCommand`.
```suggestion
    // See `AnyAsyncCommand`.
```

2022-01-18 12:16 UTC, 0xTim commented on Sources/ConsoleKit/Command/Completion.swift
> +    // See `AnyCommand`.
```suggestion
    // See `AnyAsyncCommand`.
```

2022-01-18 12:16 UTC, 0xTim commented on Sources/ConsoleKit/Command/Console+Run.swift
> +          return try command.run(using: &context)
Nit spacing
```suggestion
            return try command.run(using: &context)
```

2022-01-18 12:16 UTC, 0xTim commented on Sources/ConsoleKit/Command/Console+Run.swift
> +    public func run(_ command: AnyAsyncCommand, input: CommandInput) async throws {
This will need to be wrapped in compiler directives for 5.2-5.4

2022-01-18 12:16 UTC, 0xTim commented on Sources/ConsoleKit/Command/Console+Run.swift
> +    ///     - command: `CommandGroup` or `Command` to run.
```suggestion
    ///     - command: `AsyncCommandGroup` or `AsyncCommand` to run.
```

2022-01-18 12:16 UTC, 0xTim commented on Sources/ConsoleKit/Command/Console+Run.swift
> +    /// Runs an `AnyCommand` (`CommandGroup` or `Command`) of commands on this `Console` using the supplied `CommandInput`.
```suggestion
    /// Runs an `AnyAsyncCommand` (`AsyncCommandGroup` or `AsyncCommand`) of commands on this `Console` using the supplied `CommandInput`.
```

2022-01-18 12:16 UTC, 0xTim commented on Sources/ConsoleKit/Command/Console+Run.swift
> +    /// Runs an `AnyCommand` (`CommandGroup` or `Command`) of commands on this `Console` using the supplied `CommandContext`.
```suggestion
    /// Runs an `AnyAsyncCommand` (`AsyncCommandGroup` or `AsyncCommand`) of commands on this `Console` using the supplied `CommandContext`.
```

2022-01-18 12:16 UTC, 0xTim commented on Sources/ConsoleKit/Command/Console+Run.swift
> +    ///     - runnable: `CommandGroup` or `Command` to run.
```suggestion
    ///     - runnable: `AsyncCommandGroup` or `AsyncCommand` to run.
```

2022-01-18 12:16 UTC, 0xTim commented on Sources/ConsoleKit/Command/Console+Run.swift
> +    public func run(_ command: AnyAsyncCommand, with context: CommandContext) async throws {
Again needs wrapping in compiler directives

2022-01-18 12:16 UTC, 0xTim commented on Sources/ConsoleKit/Command/Async/AnyAsyncCommand.swift
> +public protocol AnyAsyncCommand {
This will need wrapping in compiler directives so the library still compiles in 5.2-5.4 and then anything that touches this

2022-01-18 12:16 UTC, 0xTim commented on Sources/ConsoleKitAsyncExample/main.swift
> +@main struct Main {
This will probably need wrapping to make it compile

2022-02-21 18:23 UTC, mamouneyya commented
Curious, is there anything else that's blocking this to be merged, other than the docs fixes and the directives? It would be really great to have this change.

On a related note, anyone has a way to get this working with the current code? Obviously adding the `async` keyword breaks the `Command` protocol conformance, and wrapping everything inside a `Task` is leading to immediate exit. 😞

2022-02-24 11:07 UTC, 0xTim commented
@mamouneyya yeah it's waiting on the review comments to be addressed and getting CI to pass.

For a workaround you could run your async code in a future and use `wait()` to block and wait for it to complete. It's a bit clunky but should work

2022-02-24 16:29 UTC, twof commented
I'm going to be busy for the next couple weeks unfortunately, but I'll see if I can find some time on the weekend.

2022-05-20 09:33 UTC, 0xTim commented
This has been incorporated into #170

2022-05-20 09:33 UTC, closed without merging