Modify the`AsyncCommand` implementation `Command` to support asynchronous methods through `EventLoopPromise`, so as to support the `Command` of vapor to support asynchronous methods
vapor/console-kit pull request #175
Opened 2022-06-23 01:17 UTC by josercc

```swift
@available(macOS 12, iOS 15, watchOS 8, tvOS 15, *)
final class TestCommand: AsyncCommand {
    struct Signature: CommandSignature {
        @Argument(name: "foo", help: """
        A foo is required
        An error will occur if none exists
        """)
        var foo: String

        @Option(name: "bar", short: "b", help: """
        Add a bar if you so desire
        Try passing it
        """)
        var bar: String?

        @Flag(name: "baz", short: "B", help: """
        Add a baz if you so desire
        It's just a flag
        """)
        var baz: Bool

        init() { }
    }

    let help: String = "This is a test command"

    func run(using context: CommandContext, signature: Signature) async throws {
        XCTAssertEqual(signature.$foo.name, "foo")
        XCTAssertEqual(signature.$bar.name, "bar")
        XCTAssertEqual(signature.$baz.name, "baz")
        context.console.output("Foo: \(signature.foo) Bar: \(signature.bar ?? "nil")".consoleText(.info))
    }
}
```

Because the bottom layer of `AsyncCommand` implements `Command`, I deleted some unnecessary classes

2023-03-29 09:10 UTC, oscarvgg approved these changes
This should have been the implementation of AsyncCommand from the start

2023-08-13 00:42 UTC, t-ae requested changes
There's use of `AsyncCommand` left and it blocks compile.
https://github.com/josercc/console-kit/blob/async-command/Sources/ConsoleKitAsyncExample/entry.swift#L11C1-L11C1

Documentation also needs change.
https://github.com/josercc/console-kit/blob/async-command/Sources/ConsoleKit/Command/Async/AsyncCommand.swift#L53

2023-08-13 00:46 UTC, t-ae requested changes

2023-08-13 00:46 UTC, t-ae commented on Sources/ConsoleKit/Command/Async/AsyncCommand.swift
> +    func run(usingAsync context: CommandContext, signature: Signature) async throws
This can be `func run(using context: CommandContext, signature: Signature) async throws`.

2023-08-19 03:53 UTC, gwynne commented
@josercc Can you resolve the conflicts with `main` (preferably by rebase, but whatever method you feel best able to work with is fine)

2023-08-21 08:42 UTC, josercc commented
> @josercc Can you resolve the conflicts with `main` (preferably by rebase, but whatever method you feel best able to work with is fine)?

Ok, I'll try it.

2023-08-22 01:00 UTC, josercc commented
@gwynne 
Sorry, I have been using Vapor in depth when submitting, but I have stopped using it recently. During the process of merging the code, I found something that needs to be changed. I am afraid of affecting the stability of the upstream Vapor, so I withdraw this commit. At present, I have forgotten the core logic in it.

2023-08-22 01:01 UTC, closed without merging